# Server Configuration
spring.application.name=healthcare-service
server.port=8004

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=true
eureka.instance.prefer-ip-address=true

# Logging
logging.level.root=INFO
logging.level.com.example.healthcare=DEBUG
logging.level.org.hibernate=DEBUG

# ======================
# DATABASE (FIXED)
# ======================
spring.datasource.url=jdbc:postgresql://postgres:5432/healthcare_service_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ======================
# REDIS
# ======================
spring.redis.host=redis
spring.redis.port=6379

# ======================
# KAFKA
# ======================
spring.kafka.bootstrap-servers=${KAFKA_SERVERS}
spring.kafka.consumer.group-id=healthcare-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ======================
# ERROR + FILE
# ======================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.web.resources.static-locations=classpath:/uploads/images/
# ======================
# MAIL CONFIGURATION
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================
# APP CONFIGURATION
# ======================
app.meeting.base-url=${APP_MEETING_BASE_URL:http://localhost:3000}

upload.path=uploads/profile/